name: Camunda CI/CD to deploy on Prod oregn

on: workflow_dispatch
  
jobs:
  build:
    runs-on: ${{ vars.HOSTED_RUNNER_GITHUB }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: '17'
          cache: maven
      - name: Build with Maven
        run: mvn clean install 
      - name: list the target directory to check whether jar is created or not
        run: ls -alrth target
      - name: copy to the current working directory 
        run: cp target/camunda-project-1.0.0-SNAPSHOT.jar .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          application_name: ${{ vars.CAMUNDA_EB_APP_NAME_PROD }}
          environment_name: ${{ vars.CAMUNDA_EB_ENV_NAME_PROD }}
          version_label: ${{ github.ref_name }}-${{ github.run_number }}
          region: ${{ vars.AWS_REGION_ACTIVE }}
          deployment_package: camunda-project-1.0.0-SNAPSHOT.jar
